// import Navbar from "@/Components/Navbar";
import "./globals.css";
import  MyContext from "@/Helper/Context";
export const metadata = {
  title: "To Do App",
  description: "Generated by Abhiraj",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <MyContext>
          {children}
        </MyContext>
        
      </body>
    </html>
  );
}
